# Generated by Django 2.2.10 on 2021-04-23 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текст вопроса')),
                ('type_question', models.CharField(choices=[(None, 'Выберите тип вопроса'), ('text', 'Ответ текстом'), ('one_choice', 'Ответ с выбором одного варианта'), ('many_choice', 'Ответ с выбором нескольких вариантов')], max_length=11, verbose_name='Тип вопроса')),
                ('polls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Polls')),
            ],
        ),
    ]
