# Generated by Django 2.2.10 on 2021-04-27 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210423_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_date_login', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='choice',
            name='questions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice', to='polls.Questions'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='polls',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='polls.Polls'),
        ),
    ]
